spring:
  application:
    name: bookmytrip-gw
  cloud:
    gateway:
      routes:
        - id: bookmytrip-service
          uri: lb://BOOKMYTRIP-SERVICE
          predicates:
            - Path=/api/v1/admin/tickets/**

server:
  port: 9090
