spring:
  application:
    name: bookmytrip-gw
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Match all routes
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:9090"
              - "http://swagger-ui:8080"
              - "http://bookmytrip-gw:9090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: bookmytrip-service
          uri: lb://BOOKMYTRIP-SERVICE
          predicates:
            - Path=/api/v1/airlines/**,/api/v1/airports/**,/api/v1/buses/**,/api/v1/bus-operators/**,/api/v1/bus-seats/**,/api/v1/bus-terminals/**,/api/v1/bus-trips/**,/api/v1/planes/**,/api/v1/plane-seats/**,/api/v1/flights/**,/api/v1/trips/**,/api/v1/flight-tickets/**,/api/v1/tickets/**,/api/v1/bus-tickets/**,/bookmytrip-service/v3/api-docs
          filters:
            - AuthenticationFilter

        - id: bookmytrip-user-service
          uri: lb://BOOKMYTRIP-USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/roles/**,/api/v1/user-roles/**,/api/v1/account/**,/user-service/v3/api-docs
          filters:
            - AuthenticationFilter

server:
  port: 9090

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      -   name: gateway-service
          url: /v3/api-docs
      -   name: user-service
          url: /user-service/v3/api-docs
      -   name: bookmytrip-service
          url: /bookmytrip-service/v3/api-docs